#include "cassette_renderer.hpp"
void stub_open(const char*);
void stub_close();
void stub_frame(const char*);
using namespace threedsmsc;
static CassetteView base() {
  CassetteView v{};
  v.list_check.fill(-1);
  v.title = "Midnight City";
  v.artist = "M83";
  v.album = "Hurry Up, We're Dreaming";
  v.progress = 0.38f;
  v.position_ms = 84000;
  v.duration_ms = 243000;
  v.volume = 0.8f;
  v.battery_percent = 64;
  v.library_tracks = 1284;
  v.queue_tracks = 14;
  v.seek_seconds = 10;
  v.playing = true;
  v.has_track = true;
  v.reel_phase = 0.4f;
  v.library_path = "sdmc:/3dsmsc/music/";
  v.status = "Library ready: 1284 tracks";
  return v;
}
int main(int, char** argv) {
  stub_open(argv[1]);
  CassetteRenderer r;
  r.init();
  CassetteView e = base();
  e.eq_visible = true;
  e.eq_enabled = true;
  e.eq_selected = 3;
  e.eq_gains = {5, 4, 2, -1, -4, -1, 2, 4, 5, 10};
  e.eq_preset = "Custom";
  stub_frame("eq");
  r.render(e);
  CassetteView eo = e;
  eo.eq_enabled = false;
  eo.light_theme = true;
  eo.eq_selected = 6;
  eo.eq_gains = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
  eo.eq_preset = "Flat";
  stub_frame("eq_off_light");
  r.render(eo);
  CassetteView h = base();
  stub_frame("home");
  r.render(h);
  CassetteView bp = base();
  bp.battery_display = 2;
  bp.battery_charging = true;
  bp.headphones = true;
  stub_frame("home_percent_charging_headphones");
  r.render(bp);
  CassetteView bl = base();
  bl.battery_percent = 9;
  bl.headphones = true;
  bl.light_theme = true;
  stub_frame("home_low_icon_light");
  r.render(bl);
  CassetteView a = base();
  a.list_visible = true;
  a.list_heading = "Settings";
  a.list_total = 10;
  a.list_position = 4;
  a.list_count = 5;
  a.list_selected = 4;
  a.list_items = {"SOUND", "Seek step: 10 s", "Background playback: on", "UI",
                  "Reel animation: on"};
  a.list_check = {-2, -1, -1, -2, -1};
  a.status = "A selects, B goes back";
  stub_frame("settings_mid");
  r.render(a);
  CassetteView b2 = base();
  b2.light_theme = true;
  b2.list_visible = true;
  b2.list_heading = "Settings";
  b2.list_total = 10;
  b2.list_position = 1;
  b2.list_count = 5;
  b2.list_selected = 1;
  b2.list_items = {"LIBRARY", "Full scan again", "Music folders: sdmc:/3dsmsc/music/  (default)",
                   "SOUND", "Equalizer: Rock"};
  b2.list_check = {-2, -1, -1, -2, -1};
  b2.status = "A selects, B goes back";
  stub_frame("settings_top_light");
  r.render(b2);
  CassetteView q = base();
  q.shuffle = true;
  q.repeat_mode = 1;
  q.list_visible = true;
  q.list_heading = "Queue";
  q.list_total = 16;
  q.list_position = 0;
  q.list_count = 5;
  q.list_selected = 0;
  q.list_sub_selected = 1;
  q.list_items = {"", "TRACKS", "Midnight City", "Reunion", "Wait"};
  q.list_check = {-3, -2, -1, -1, -1};
  q.status = "14 tracks queued";
  stub_frame("queue_modes");
  r.render(q);
  CassetteView q2 = q;
  q2.list_selected = 2;
  q2.list_position = 3;
  q2.repeat_mode = 0;
  q2.shuffle = false;
  q2.light_theme = true;
  stub_frame("queue_modes_light");
  r.render(q2);
  CassetteView hm = base();
  hm.shuffle = false;
  hm.repeat_mode = 1;
  stub_frame("home_repeat");
  r.render(hm);
  CassetteView t = base();
  stub_frame("remaining");
  r.render(t);
  CassetteView m1 = base();
  m1.shuffle = true;
  m1.repeat_mode = 2;
  stub_frame("modes_shuf_one");
  r.render(m1);
  CassetteView m2 = base();
  m2.shuffle = false;
  m2.repeat_mode = 0;
  m2.light_theme = true;
  stub_frame("modes_off_light");
  r.render(m2);
  CassetteView m3 = base();
  m3.shuffle = false;
  m3.repeat_mode = 1;
  stub_frame("modes_all");
  r.render(m3);
  CassetteView hp = base();
  hp.headphones = true;
  stub_frame("headphones");
  r.render(hp);
  CassetteView hpl = hp;
  hpl.light_theme = true;
  stub_frame("headphones_light");
  r.render(hpl);
  CassetteView ab = base();
  ab.list_visible = true;
  ab.list_heading = "About this";
  ab.list_total = 12;
  ab.list_position = 0;
  ab.list_count = 5;
  ab.list_selected = 0;
  ab.list_items = {"3DSMSC", "Version 0.4.2b", "An offline music player for the 3DS", "CREDITS",
                   "Created by @mcrx0"};
  ab.list_check = {-2, -4, -4, -2, -4};
  ab.status = "B goes back";
  stub_frame("about_top");
  r.render(ab);
  CassetteView ab2 = ab;
  ab2.list_position = 5;
  ab2.list_items = {"and a lot of iterations with LLMs", "THIRD PARTY", "minimp3, minimp4 (CC0)",
                    "dr_flac (Unlicense / MIT-0)", "FAAD2 (GPL-2.0 or later)"};
  ab2.list_check = {-4, -2, -4, -4, -4};
  ab2.light_theme = true;
  stub_frame("about_light");
  r.render(ab2);
  CassetteView st = base();
  st.list_visible = true;
  st.list_heading = "Settings";
  st.list_total = 12;
  st.list_position = 10;
  st.list_count = 3;
  st.list_selected = 2;
  st.list_items = {"Theme: dark", "MISC", "About this", "", ""};
  st.list_check = {-1, -2, -1, -1, -1};
  st.status = "A selects, B goes back";
  stub_frame("settings_misc");
  r.render(st);
  CassetteView c1 = base();
  c1.list_visible = true;
  c1.list_heading = "Button mapping";
  c1.list_total = 26;
  c1.list_position = 0;
  c1.list_count = 5;
  c1.list_selected = 0;
  c1.list_items = {"HOME", "A|Play or pause", "X|Next track", "Y|Previous track",
                   "D-pad L/R|Seek back / forward"};
  c1.list_check = {-2, -5, -5, -5, -5};
  c1.status = "D-pad scrolls, B goes back";
  stub_frame("controls_top");
  r.render(c1);
  CassetteView c2 = c1;
  c2.list_position = 19;
  c2.light_theme = true;
  c2.list_items = {"D-pad U/D|Raise / lower the gain", "A|Switch on or off", "X|Next preset",
                   "Y|Reset to flat", "B|Go back"};
  c2.list_check = {-5, -5, -5, -5, -5};
  stub_frame("controls_light");
  r.render(c2);
  stub_close();
  return 0;
}
